apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          value: "Abcdef@.123456"
        ports:
        - containerPort: 1433
       volumeMounts:
       - name: mssqldb
         mountPath: /mnt/data
     volumes:
     - name: mssqldb
       persistentVolumeClaim:
         claimName: mssql-pv-claim

---
apiVersion: v1
kind: Service
metadata:
  name: mssql
  namespace: default
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433